In [1]:
import pandas as pd
import os
import gc

In [2]:
# Comando para poder ubicar nuestra ruta actual del proyecto, util en grandes proyecto para poder manejar rutas relativas 
path_project = os.getcwd()
print(path_project)

c:\Users\Pipicano\Music\Semester I\Proyecto RCV\RCV\scripts

In [3]:
df = pd.read_parquet(os.path.join(path_project, '..', 'data', 'processed', 'df_complete_archivo.parquet'))

In [4]:
df

,col_760010395712,consecutivo,col_1,col_2,fehca_de_inscripcion,año,fecha_ultima_atención,ips,1_primernombre,2_segundonombre,...,41_programateerc_(nefroproteccion),endosalud,79_novedad,80_causamuerte,81_fechamuerte,82_glicemia,82_1_fecha_glicemia,83_trigliceridos,83_1_fecha_trigliceridos,unnamed:_0
0,760010395729,1,0,167,<NA>,2014,2014-01-02,PS COMUNEROS I,AQUILINO,NONE,...,<NA>,NO,<NA>,<NA>,<NA>,130,2015-10-09,213,2015-10-09,<NA>
1,760010395725,2,0,165,<NA>,2014,2014-01-02,PS CALIPSO,LUIS,EDUARDO,...,<NA>,SI,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,760010395706,3,0,167,<NA>,2014,2014-01-02,PS CALIPSO,ZORAIDA,DE JESUS,...,<NA>,NO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,760010395720,4,0,144,<NA>,2014,2014-01-07,CS VALLADO,JULIA,ALICIA,...,<NA>,NO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,760010395725,5,0,160,<NA>,2018,2018-03-08,PS CALIPSO,MARIA,DEL SOCORRO,...,<NA>,NO,<NA>,<NA>,<NA>,112,2018-03-06,138,2018-03-06,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656570,<NA>,32260,0,<NA>,2018-09-19,2018,2018-09-19,PS CALIPSO,EDILBERTO,NONE,...,<NA>,NO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
656571,<NA>,32261,0,<NA>,2018-09-06,2018,2018-09-06,CS DESEPAZ,MIGUEL,ANTONIO,...,<NA>,NO,<NA>,<NA>,<NA>,326,2018-09-05,166.0,2018-09-05,<NA>
656572,<NA>,32262,0,<NA>,2018-09-14,2018,2018-09-14,CS DESEPAZ,LUIS,EDUARDO,...,<NA>,NO,<NA>,<NA>,<NA>,127,2018-09-17,101.0,2018-09-17,<NA>
656573,<NA>,32263,0,<NA>,2018-09-11,2018,2018-09-11,CS DESEPAZ,JOHN,JAIRO,...,<NA>,NO,<NA>,<NA>,<NA>,187,2018-10-03,209.0,2018-10-03,<NA>
656574,<NA>,32264,0,<NA>,2018-09-28,2018,2018-09-28,CS MANUELA,CESAR,AUGUSTO,...,<NA>,NO,<NA>,<NA>,<NA>,133,2018-09-14,219.0,2018-05-29,<NA>

In [7]:
for col in df.columns:
    print(col, '->', pd.api.types.infer_dtype(df[col], skipna=True))

col_760010395712 -> string
consecutivo -> string
col_1 -> string
col_2 -> string
fehca_de_inscripcion -> string
año -> string
fecha_ultima_atención -> string
ips -> string
1_primernombre -> string
2_segundonombre -> string
3_primerapellido -> string
4_segundoapellido -> string
5_tipoidentificacion -> string
6_identificacion -> string
7_fechanac -> string
edad_(años_cumplidos) -> string
grupo_edad -> string
8_sexo -> string
9_regimen -> string
10_eps -> string
11_codetnia -> string
12_grupopob -> string
metodo_de_planificacion -> string
13_codmun -> string
14_telefono -> string
direccion -> string
15_fechaafileps -> string
16_codipssegto -> string
17_fechainnefro -> string
18_dxhta -> string
clasificación_hta -> string
20_dxdm -> string
clasificación_dm -> string
22_etiologiaerc -> string
23_peso -> string
24_talla -> string
indice_masa_corporal_=_peso/talla_al_cuadrado -> string
clasificación_imc -> string
sedentario -> string
cigarrillo -> string
sobrepeso -> string
obesidad -> string
alcohol -> string
aliment_inadecuada_(sal,_pocas_frutas_y_verduras) -> string
25_tenartsis -> string
26_tenartditlica -> string
clasificacion_final_del_riesgo -> string
27_creatinina -> string
27_1_fechacrea -> string
28_hemoglicosilada -> string
28_1_fechahemoglico -> string
29_albuminuria -> string
29_1_fechaalbnuria -> string
30_creatinuria -> string
30_fechacreatinuria -> string
31_colesteroltotal -> string
31_1_fechact -> string
32_hdl -> string
32_1_fechahdl -> string
33_ldl -> string
33_1_fechaldl -> string
35_tfg -> string
36_rcbeieca -> string
37_rcbeara2 -> string
38_dxerc -> string
40_fechadxerc -> string
41_programateerc_(nefroproteccion) -> string
endosalud -> string
79_novedad -> string
80_causamuerte -> string
81_fechamuerte -> string
82_glicemia -> string
82_1_fecha_glicemia -> string
83_trigliceridos -> string
83_1_fecha_trigliceridos -> string
unnamed:_0 -> string

In [8]:
df.isnull().sum()

col_760010395712            258889
consecutivo                      0
col_1                       118297
col_2                       238237
fehca_de_inscripcion        378988
                             ...
82_glicemia                 242336
82_1_fecha_glicemia         242336
83_trigliceridos            244640
83_1_fecha_trigliceridos    244640
unnamed:_0                  656575
Length: 76, dtype: int64

In [9]:
print(df['consecutivo'])

0             1
1             2
2             3
3             4
4             5
          ...
656570    32260
656571    32261
656572    32262
656573    32263
656574    32264
Name: consecutivo, Length: 656575, dtype: string

Teniendo en cuenta la gran cantidad de vaiables se procede a seleccionar las variables desde un concepto medico

* Variables demográficas:

edad_(años_cumplidos) - Factor de riesgo primario
8_sexo - Diferencias en riesgo por género
7_fechanac - Para cálculos de edad precisos

* Variables clínicas directas:

18_dxhta + clasificación_hta - Hipertensión (factor mayor)
20_dxdm + clasificación_dm - Diabetes mellitus (factor mayor)
25_tenartsis + 26_tenartditlica - Presión arterial sistólica/diastólica

* Variables metabólicas:

31_colesteroltotal - Colesterol total
32_hdl - Colesterol HDL (protector)
33_ldl - Colesterol LDL (aterogénico)
83_trigliceridos - Triglicéridos
82_glicemia - Glucemia
28_hemoglicosilada - HbA1c (control glucémico)

* Variables antropométricas:

23_peso, 24_talla, indice_masa_corporal_=_peso/talla_al_cuadrado
clasificación_imc - Obesidad como factor de riesgo

* Variables de estilo de vida:

sedentario, cigarrillo, alcohol
aliment_inadecuada_(sal,_pocas_frutas_y_verduras)
sobrepeso, obesidad

* Variables renales (riesgo cardiovascular-renal):

27_creatinina + 35_tfg - Función renal
29_albuminuria - Daño renal/vascular