In [1]:
import polars as pl
import pandas as pd

In [3]:
df = pl.read_parquet('../data/raw/archivo 3/Reporte Cronicos ESE Oriente ABRIL 2023.parquet').to_pandas()
df

,comuna,consecutivo,cruce_poblacion_asignada,1900_01_02_00:00:00,fecha_de_inscripcion,año,fecha_ultima_atención,ips,1_primernombre,2_segundonombre,...,consumo_sustancias_psicoactivas,fecha_proxima_cita,profesional_que_atendera_(medico_o_enfermera),resultado_penultima_creatinina,fecha_resultado_penultima_creatinina,resultado_penultima_rac,fecha_resultado_penultima_rac,resultado_penultima_rac.1,fecha_resultado_penultima_rac.1,estatina
0,COMUNA 15,1,None,None,1800-01-01,2014,2014-01-02,PS COMUNEROS I,AQUILINO,NONE,...,No,None,None,None,None,None,None,None,None,None
1,COMUNA 13,2,None,None,1800-01-01,2014,2014-01-02,PS CALIPSO,LUIS,EDUARDO,...,No,None,None,None,None,None,None,None,None,None
2,COMUNA 13,3,None,None,1800-01-01,2014,2014-01-02,PS CALIPSO,ZORAIDA,DE JESUS,...,No,None,None,None,None,None,None,None,None,None
3,COMUNA 15,4,None,None,1800-01-01,2014,2014-01-07,CS VALLADO,JULIA,ALICIA,...,No,None,None,None,None,None,None,None,None,None
4,COMUNA 13,5,None,None,1800-01-01,2019,2019-12-05,PS CALIPSO,MARIA,DEL SOCORRO,...,No,None,None,0.64,2018-11-30,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43186,HOSPITAL,43187,None,None,2023-04-14 00:00:00,2023,2023-04-14,HOSPITAL,JENNIFER,YINET,...,No,2023-05-11,Medico,None,None,None,None,None,None,None
43187,HOSPITAL,43188,31301168,None,2023-04-17 00:00:00,2023,2023-04-17,HOSPITAL,EDILMA,NONE,...,No,2023-05-17,Medico,0.73,2022-03-04,None,None,None,None,Atorvastatina 20 mg-C10AA0502
43188,HOSPITAL,43189,16751387,None,2023-04-18 00:00:00,2023,2023-04-18,HOSPITAL,ALVEIRO,NONE,...,No,2023-05-18,Medico,None,None,None,None,None,None,None
43189,HOSPITAL,43190,None,None,2023-04-19 00:00:00,2023,2023-04-19,HOSPITAL,JORGE,NONE,...,No,2023-05-19,Enfermera,None,None,None,None,None,None,Atorvastatina 40 mg TABLETA-C10AA0503
43190,COMUNA 15,43191,31603429,None,2023-04-21 00:00:00,2023,2023-04-21,CS VALLADO,LUCIA,NONE,...,No,2023-05-24,Medico,None,None,None,None,None,None,None

In [4]:
df.describe()

,comuna,consecutivo,cruce_poblacion_asignada,1900_01_02_00:00:00,fecha_de_inscripcion,año,fecha_ultima_atención,ips,1_primernombre,2_segundonombre,...,consumo_sustancias_psicoactivas,fecha_proxima_cita,profesional_que_atendera_(medico_o_enfermera),resultado_penultima_creatinina,fecha_resultado_penultima_creatinina,resultado_penultima_rac,fecha_resultado_penultima_rac,resultado_penultima_rac.1,fecha_resultado_penultima_rac.1,estatina
count,43191,43191,31062,9,43191,43191,43191,43191,43191,43191,...,43191,37092,37092,31369,31369,2949,2949,1126,1126,12046
unique,5,43191,31062,9,2358,10,2185,25,4986,3713,...,2,2262,2,664,2364,431,468,166,253,23
top,COMUNA 14,1,25592695,4.9,1800-01-01,2023,2023-04-17,HOSPITAL,MARIA,NONE,...,No,2023-06-20,Medico,0.8,2022-03-01,0.3,2022-02-21,0.4,2020-10-08,Atorvastatina 40 mg TABLETA-C10AA0503
freq,10372,1,1,1,7535,19441,490,7710,5576,18288,...,43059,1725,24389,628,281,301,44,115,20,5686

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43191 entries, 0 to 43190
Columns: 101 entries, comuna to estatina
dtypes: object(101)
memory usage: 33.3+ MB

In [33]:
print([col for col in df.columns if 'aten' in col.lower()])
print([col for col in df.columns ])

['fecha_ultima_atención', 'profesional_que_atendera_(medico_o_enfermera)']
['comuna', 'consecutivo', 'cruce_poblacion_asignada', '1900_01_02_00:00:00', 'fecha_de_inscripcion', 'año', 'fecha_ultima_atención', 'ips', '1_primernombre', '2_segundonombre', '3_primerapellido', '4_segundoapellido', '5_tipoidentificacion', '6_identificacion', '7_fechanac', 'edad_(años_cumplidos)', 'grupo_edad', '8_sexo', '9_regimen', '10_eps', '11_codetnia', '12_grupopob', 'metodo_de_planificacion', '13_codmun', '14_telefono', 'direccion', '15_escolaridad', '16_codipssegto', 'zona', '18_dxhta', 'tipo_de_consulta_y_profesional', '20_dxdm', 'clasificación_dm', '22_etiologiaerc', '23_peso', '24_talla', 'indice_masa_corporal_=_peso/talla_al_cuadrado', 'clasificación_imc', 'sedentario', 'cigarrillo', 'sobrepeso', 'obesidad', 'alcohol', 'aliment_inadecuada_(sal,_pocas_frutas_y_verduras)', '25_tenartsis', '26_tenartditlica', 'clasificacion_final_del_riesgo', '27_creatinina', '27_1_fechacrea', '28_hemoglicosilada', '28_1_fechahemoglico', '29_albuminuria', '29_1_fechaalbnuria', '30_creatinuria', '30_fechacreatinuria', '31_colesteroltotal', '31_1_fechact', '32_hdl', '32_1_fechahdl', '33_ldl', '33_1_fechaldl', '35_tfg', '36_rcbeieca', '37_rcbeara2', '38_dxerc', '40_fechadxerc', '41_programateerc_(nefroproteccion)', 'endosalud', '79_novedad', '81_fechamuerte', '80_causamuerte', '82_glicemia', '82_1_fecha_glicemia', '83_trigliceridos', '83_1_fecha_trigliceridos', '84_cociente_albuminuria/creatinuria', '84_1_cociente_albuminuria/creatinuria', 'proteinas_0_15', 'eritrocitos_0_18_mgd', 'cilindros_patologicos', 'analisis_uroanalisis', 'fecha_uroanalisis', 'fecha_electrocardiograma', 'fecha_consulta_medicina_familiar', 'fecha_consulta_medicina_interna', 'fecha_consulta_psicologia', 'fecha_consulta_nutricion', 'perimetro_abdominal', 'perimetro_de_cadera', 'adherencia_a_tratamiento_(morisky_green', 'conocimiento_de_la_enfermedad(test_de_batalla)', 'consumo_sustancias_psicoactivas', 'fecha_proxima_cita', 'profesional_que_atendera_(medico_o_enfermera)', 'resultado_penultima_creatinina', 'fecha_resultado_penultima_creatinina', 'resultado_penultima_rac', 'fecha_resultado_penultima_rac', 'resultado_penultima_rac.1', 'fecha_resultado_penultima_rac.1', 'estatina']

In [17]:
df['23_peso']

0        75.0
1        95.0
2        64.0
3        64.0
4        82.0
         ...
43186    62.0
43187    67.0
43188    58.0
43189    66.0
43190    75.0
Name: 23_peso, Length: 43191, dtype: object

In [20]:
print(df['23_peso'].isnull())

0        False
1        False
2        False
3        False
4        False
         ...
43186    False
43187    False
43188    False
43189    False
43190    False
Name: 23_peso, Length: 43191, dtype: bool

In [35]:
df_1 = df[[
    '6_identificacion',
    'edad_(años_cumplidos)',
    '8_sexo',
    '25_tenartsis',
    '31_colesteroltotal',
    '31_1_fechact',
    '32_hdl',
    '32_1_fechahdl',
    'cigarrillo',
    '20_dxdm',
    '36_rcbeieca',
    '37_rcbeara2',
    'fecha_ultima_atención',
    'estatina',
    '23_peso',
    '24_talla'
 ]]
df_1

,6_identificacion,edad_(años_cumplidos),8_sexo,25_tenartsis,31_colesteroltotal,31_1_fechact,32_hdl,32_1_fechahdl,cigarrillo,20_dxdm,36_rcbeieca,37_rcbeara2,fecha_ultima_atención,estatina,23_peso,24_talla
0,4740904,82,M,130,None,None,26.0,2015-10-09,None,NO,NO,NO,2014-01-02,None,75.0,167.0
1,16739096,55,M,130,None,None,None,None,No,NO,NO,NO,2014-01-02,None,95.0,165.0
2,31904760,66,F,160,None,None,None,None,No,NO,NO,NO,2014-01-02,None,64.0,161.0
3,178199,78,F,160,None,None,None,None,No,SI,NO,NO,2014-01-07,None,64.0,160.0
4,43643679,55,F,110,209.0,2019-04-03,37.0,2019-04-03,No,SI,NO,NO,2019-12-05,None,82.0,160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43186,1087198944,31,F,110,None,None,None,None,No,SI,NO,NO,2023-04-14,None,62.0,164.0
43187,31301168,69,F,110,197.94,2023-02-20,55.4,2023-02-20,No,SI,NO,NO,2023-04-17,Atorvastatina 20 mg-C10AA0502,67.0,152.0
43188,16751387,55,M,110,249.01,2023-04-10,None,None,No,SI,NO,NO,2023-04-18,None,58.0,157.0
43189,10165352,67,M,110,159.05,2023-03-30,40.77,2023-03-30,None,SI,NO,NO,2023-04-19,Atorvastatina 40 mg TABLETA-C10AA0503,66.0,172.0
43190,31603429,37,F,120,None,None,None,None,None,SI,NO,NO,2023-04-21,None,75.0,162.0

In [43]:
# 30 - 74 años
df['edad_(años_cumplidos)'].describe()

count     43191
unique      103
top          64
freq       1235
Name: edad_(años_cumplidos), dtype: object

In [44]:
df['edad_(años_cumplidos)'].min()

'10'

In [46]:
df['25_tenartsis'].describe()

count     43191
unique      133
top         120
freq      12378
Name: 25_tenartsis, dtype: object

In [47]:
df['25_tenartsis'].min()

'100'

In [48]:
df['31_colesteroltotal'].describe()

count     39770
unique    12682
top       175.0
freq        178
Name: 31_colesteroltotal, dtype: object

In [54]:
df['estatina'].unique()

array([None, 'Atorvastatina 40 mg TABLETA-C10AA0503',
       'Atorvastatina 20 mg-C10AA0502', 'ATORVASTATINA 40MG-U001293',
       'ROSUVASTATINA 40 MG TABLETAS RECUBIERTAS-058653',
       'ATORVASTATINA20MG-U_000516',
       'ACIDO FENOFIBRICO + ROSUVASTATINA 135 MG/ 5 MG CAPSULAS-058658',
       'ROSUVASTATINA 20 MG TABLETAS RECUBIERTAS-058652',
       'LOVASTATINA20MG-U_000600',
       'ACIDO FENOFIBRICO + ROSUVASTATINA 135 MG/ 20 MG CAPSULAS-058660',
       'LOVASTATINA 20 MG-51137',
       'EZETIMIBE + ROSUVASTATINA 10MG/20MG TABLETAS RECUBIERTAS-058654',
       'Atorvastatina 10 mg-C10AA0501',
       'ACIDO FENOFIBRICO + ROSUVASTATINA 135 MG/ 10 MG CAPSULAS-058659',
       'EZETIMIBE 10MG ATORVASTATINA 20MG TABLETA-C10AX091',
       'EZETIMIBE 10 MG ROSUVASTATINA 40 MG TABLETAS-C10AX093',
       'Lovastatina-20 mg tableta-B04AL018011',
       'ROSUVASTATINA 10 MG TABLETAS RECUBIERTAS-058651',
       'EZETIMIBE 10+ ATORVASTATINA 40 MG-C10AX09',
       'EZETIMIBE + SIMVASTATINA 10 MG/40 MG TABLETAS-058648',
       'ATORVASTATINA10MG-U_000593',
       'EZETIMIBE + SIMVASTATINA 10 MG/80 MG TABLETAS-058649',
       'EZETIMIBE + SIMVASTATINA 10 MG/20 MG TABLETAS-058647',
       'ATORVASTATINA20MG-U_000588'], dtype=object)

In [55]:
print(df_1.dtypes)

6_identificacion         object
edad_(años_cumplidos)    object
8_sexo                   object
25_tenartsis             object
31_colesteroltotal       object
31_1_fechact             object
32_hdl                   object
32_1_fechahdl            object
cigarrillo               object
20_dxdm                  object
36_rcbeieca              object
37_rcbeara2              object
fecha_ultima_atención    object
estatina                 object
23_peso                  object
24_talla                 object
dtype: object

In [58]:
dic_type = {
    '6_identificacion': 'string',
    'edad_(años_cumplidos)': 'Int64',
    '8_sexo': 'category',
    '25_tenartsis': 'Float32',
    '31_colesteroltotal': 'Float32',
    '31_1_fechact': 'string',
    '32_hdl': 'Float32',
    '32_1_fechahdl': 'string',
    'cigarrillo': 'category',
    '20_dxdm': 'category',
    '36_rcbeieca': 'category',
    '37_rcbeara2': 'category',
    'fecha_ultima_atención': 'string',
    'estatina': 'category',
    '23_peso': 'Float32',
    '24_talla': 'Float32'
}
df_1 = df_1.astype(dic_type)
df_1.dtypes

6_identificacion         string[python]
edad_(años_cumplidos)             Int64
8_sexo                         category
25_tenartsis                    Float32
31_colesteroltotal              Float32
31_1_fechact             string[python]
32_hdl                          Float32
32_1_fechahdl            string[python]
cigarrillo                     category
20_dxdm                        category
36_rcbeieca                    category
37_rcbeara2                    category
fecha_ultima_atención    string[python]
estatina                       category
23_peso                         Float32
24_talla                        Float32
dtype: object

In [62]:
correlacion = df_1.corr(numeric_only=True)
correlacion

,edad_(años_cumplidos),25_tenartsis,31_colesteroltotal,32_hdl,23_peso,24_talla
edad_(años_cumplidos),1.000000,0.059746,-0.023240,0.043058,-0.361859,-0.202903
25_tenartsis,0.059746,1.000000,0.067025,0.032330,0.062978,0.019918
31_colesteroltotal,-0.023240,0.067025,1.000000,0.260970,-0.027449,-0.045746
32_hdl,0.043058,0.032330,0.260970,1.000000,-0.098019,-0.045285
23_peso,-0.361859,0.062978,-0.027449,-0.098019,1.000000,0.401595
24_talla,-0.202903,0.019918,-0.045746,-0.045285,0.401595,1.000000

In [ ]:
# Reglas de validación
# Edad entre 30 y 74 años
# Tenartsis entre 70 y 260

In [64]:
import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import roc_auc_score, average_precision_score, brier_score_loss

# -------- 0) Carga y features --------
# df = ... (tipificado como ya definimos)
df = df[df['edad_(años_cumplidos)'].between(30,74)].copy()

# Etiqueta (ejemplo: alto riesgo si clasificacion_final_del_riesgo == 'Alto')
# Si no existe, reemplaza 'label' por la etiqueta derivada de Framingham.
label_col = 'label_alto_rcv'  # crea esta columna antes
# df[label_col] = (df['clasificación_final_del_riesgo'].str.contains('Alto', case=False, na=False)).astype(int)

# Features (sin lípidos, cobertura)
df['imc'] = df['23_peso'] / (df['24_talla']**2)
df['hta_tratada'] = df[['36_rcbeieca','37_rcbeara2']].any(axis=1).astype(int)

X = df[['edad_(años_cumplidos)','8_sexo','25_tenartsis','imc','cigarrillo','20_dxdm','hta_tratada']].copy()
y = df[label_col].astype(int)

# Separar tipos
num_cols = ['edad_(años_cumplidos)','25_tenartsis','imc']
cat_cols = ['8_sexo','cigarrillo','20_dxdm','hta_tratada']  # binarios tratados como categóricos o numéricos; ambas opciones valen

pre = ColumnTransformer([
    ('num', 'passthrough', num_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore', drop=None), cat_cols),
])

base = LogisticRegression(max_iter=200, class_weight='balanced', solver='liblinear')

# Pipeline + calibración (Isotonic suele calibrar mejor)
clf = Pipeline([
    ('prep', pre),
    ('model', CalibratedClassifierCV(base, cv=5, method='isotonic'))
])

X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
clf.fit(X_tr, y_tr)

# -------- 1) Evaluación --------
p_te = clf.predict_proba(X_te)[:,1]
print("AUROC:", roc_auc_score(y_te, p_te).round(3))
print("AUPRC:", average_precision_score(y_te, p_te).round(3))
print("Brier:", brier_score_loss(y_te, p_te).round(3))

# -------- 2) Prevalencia total y por segmento --------
def prevalencia(p):
    return float(np.nanmean(p))

prev_total = prevalencia(p_te)
print("Prevalencia estimada (test):", round(prev_total, 3))

# Por segmentos (ej. zona y comuna)
seg_cols = []
for col in ['Zona','COMUNA']:  # reemplaza con tus nombres exactos si están en X_te
    if col in df.columns:
        seg_cols.append(col)

if seg_cols:
    te_index = X_te.index
    df_seg = df.loc[te_index, seg_cols].copy()
    df_seg['p'] = p_te
    tabla = df_seg.groupby(seg_cols)['p'].mean().reset_index().rename(columns={'p':'prevalencia_estimada'})
    print(tabla.head())

TypeError: '>=' not supported between instances of 'str' and 'int'